[tool.poetry]
name = "project1"
version = "0.1.0"
description = ""
authors = ["AKAmaaz <inamdarmaazahmed@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
